version: '3.9'

services:
  epaper:
    build:
      context: ./docker/
      dockerfile: Dockerfile
    container_name: news24_epaper
    ports:
      - "82:80"
    volumes:
      - .:/var/www/html
    environment:
      - APACHE_DOCUMENT_ROOT=/var/www/html
    working_dir: /var/www/html/
    #command: bash -c "php ./project/composer.phar update"
    command: apache2-foreground
    depends_on:
      - epaper_db

  epaper_db:
    image: mysql:5.7
    container_name: news24_epaper_db
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: droid273
      MYSQL_DATABASE: mrnetdoptor_epaper2
      MYSQL_USER: mrnetdoptor_epaper2
      MYSQL_PASSWORD: droid273
    volumes:
      - db_data:/var/lib/mysql
      - .:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: epaper_db
      MYSQL_ROOT_PASSWORD: droid273
    depends_on:
      - epaper_db

volumes:
  db_data:

